---
- name: Configure Borg backup
  hosts: all
  become: True

  vars:

    borgbackup_cleanup: false
    borgbackup_mode: serial

    borgbackup_serial_cron_day: "*"
    borgbackup_serial_cron_hour: "23"
    borgbackup_serial_cron_minute: "00"

    borgbackup_server:
      - fqdn: localhost
        port: 2222
        type: normal
        home: /mnt/borgbackup/
        pool: repos
        options: ""

    borgbackup_retention:
      hourly: 12
      daily: 7
      weekly: 4
      monthly: 6
      yearly: 1

    borgbackup_include:
      - "/"

    borgbackup_exclude:
      - "/dev/"
      - "/proc/"
      - "/sys/"
      - "/var/run/"
      - "/run/"
      - "/mnt/"
      - "/media/"
      - "/tmp/"
      - "/lost+found"
      - "/var/log/"
      - "/var/lib/lxc*"
      - "/var/lib/mysql*"
      - "/root/.cache"
      - "/var/cache/"
      - "/var/lib/docker/devicemapper/"
      - "/var/lib/docker/overlay2/"
      - "sh:/home/*/.cache"

  roles:
    - role: borgbackup-pull
      tags: ['backup']
