---

- name: server | create dynamic meta file
  template:
    src: "meta.j2"
    dest: "{{ role_path }}/meta/main.yml"
    owner: "{{ borgbackup_client_user }}"
    group: "{{ borgbackup_client_user }}"
    mode: "0644"
  delegate_to: localhost

- set_fact:
    borgbackup_server_group: "{{ groups.borgbackup_server | default([]) }} "

- include_tasks: install.yml
  when: >
    borgbackup_required == True or
    inventory_hostname in borgbackup_server_group

- include_tasks: borg-server.yml
  when: inventory_hostname in borgbackup_server_group

- include_tasks: borg-client.yml
  when: inventory_hostname in groups['borgbackup_clients']
